import { Container, Box, Button } from "@mui/material";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { EmailRequestBody } from "./api/sendNotificationEmail";

export default function Home() {
  async function sendNotificationEmail() {

    const requestBody: EmailRequestBody = {
      emailID: "karandeepsingh00@icloud.com",
      name: "Karan",
      message: "This is a test message",
    };

    const response = await fetch("/api/sendNotificationEmail", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    });
    const data = await response.json();
    console.log(data);
  }

  return (
    <Container maxWidth="md">
      <Head>
        <title>Bookmark Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Button variant="contained" color="primary" sx={{ m: 4, textAlign: "center" }} onClick={() => signIn()}>
            Sign In
          </Button>
          <br />
          <Button variant="contained" color="primary" sx={{ textAlign: "center" }} onClick={sendNotificationEmail}>
            Send Notification Email
          </Button>
        </Box>
      </main>
    </Container>
  );
}
