import { Box, Button, Typography } from "@mui/material";
import { signIn,  } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bookmark Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Button variant="contained" color="primary" onClick={() => signIn() }>
            Sign In
          </Button>
        </Box>
      </main>
    </>
  );
}
